version: '3.9'
services:
    linuxserver:
        image: 'lscr.io/linuxserver/code-server:latest'
        restart: unless-stopped
        volumes:
            - '${PWD}/code-server:/config'
        ports:
            - '38443:8443'
        environment:
            - SUDO_PASSWORD=code-server
        container_name: code-server
        tty: true
        stdin_open: true
        
    marp-cli:
        command: '-s .'
        image: marpteam/marp-cli
        ports:
            - '37717:37717'
            - '38080:8080'
        environment:
            - LANG=$LANG
        volumes:
            - '${PWD}/code-server/workspace:/home/marp/app'
        init: true
        tty: true
        stdin_open: true
        container_name: marp
        restart: unless-stopped

    livereload:
        image: node
        container_name: marp-livereload
        working_dir: /app
        volumes:
            - '${PWD}/code-server/workspace:/app'
        command: >
            sh -c "npm install -g browser-sync && browser-sync start --proxy http://marp-cli:8080 --files '**/*' --no-open --host 0.0.0.0 --port 33000 --ui-port 33001"
        ports:
            - '33000:33000'
            - '33001:33001'
        depends_on:
            - marp-cli
        restart: unless-stopped

    nginx:
        image: nginx
        container_name: marp-nginx
        restart: unless-stopped
        depends_on:
            - livereload
            - linuxserver
        ports:
            - "38888:80"
        volumes:
            - ${PWD}/nginxconfig/nginx.conf:/etc/nginx/conf.d/default.conf
            - ${PWD}/nginxhtml:/usr/share/nginx/html